const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OBJECTS_DIR = path.join(ROOT, "assets", "objects");
const OUT_JS = path.join(ROOT, "src", "objects.generated.js");
const OUT_CSS = path.join(ROOT, "src", "objects.generated.css");

const DIR_MAP = { left: "izq", right: "der" };

function humanize(id) {
  const parts = id.split("_");
  const base = parts.filter((p) => !DIR_MAP[p]).join("_");
  const dir = parts.find((p) => DIR_MAP[p]);
  let name = NAME_MAP[base] || (base.charAt(0).toUpperCase() + base.slice(1));
  if (dir) name += " " + DIR_MAP[dir];
  return name;
}

const NAME_MAP = {
  bed: "cama",
  box: "caja",
  plant: "planta",
  shrub: "arbusto",
  sofa: "sofa",
  table: "mesa",
  carpet: "alfombra",
};

const files = fs.readdirSync(OBJECTS_DIR)
  .filter((f) => f.endsWith(".svg"))
  .sort();

const objects = files.map((f) => {
  const id = path.basename(f, ".svg");
  return { id, name: humanize(id) };
});

const js = `// Auto-generated by scripts/generate-objects.js
// Do not edit manually. Run \`node scripts/generate-objects.js\` to update.
window.__OBJECTS_DATA = ${JSON.stringify(objects, null, 2)};
`;

fs.writeFileSync(OUT_JS, js, "utf-8");

const selector = ".object-button-icon.object";
const cssRules = objects
  .filter((o) => fs.existsSync(path.join(OBJECTS_DIR, `${o.id}.svg`)))
  .map((o) => `${selector}-${o.id} {\n  background-image: url("../assets/objects/${o.id}.svg");\n}`)
  .join("\n\n");

const css = `/* Auto-generated by scripts/generate-objects.js */
/* Do not edit manually. Run \`node scripts/generate-objects.js\` to update. */

${cssRules}

.object-preview {
  width: 100%;
  height: 100%;
  background-size: contain;
  background-repeat: no-repeat;
  background-position: center;
}
`;

fs.writeFileSync(OUT_CSS, css, "utf-8");

console.log(`✓ ${objects.length} objects found`);
objects.forEach((o) => console.log(`  ${o.id}.svg → "${o.name}"`));
console.log(`\nWrote ${OUT_JS}`);
console.log(`Wrote ${OUT_CSS}`);
